### ISSUE TITLE
<insert non-offensive message here>

### ISSUE THREAD

**Issue by futilityteam** [Krutonium/OwO#71]

**Comment by Krutonium** [comment]
That's good to know!

**Comment by KoolenDasheppi** [comment]
this repo is hot af uwu

**Comment by futilityteam** [comment]
lmao hello fellow furries
edit: i remember how my acc got suspended for this

**Comment by futilityteam** [comment]
github is officially better than telegram uwu

**Comment by Krutonium** [comment]
totes macgoats
